/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        moss: {
          DEFAULT: '#2F4A3A',
          deep: '#1B2E24',
          velvet: '#3A5A47',
          soft: '#6B8A77',
          ink: '#0E1B14',
        },
        cloud: {
          DEFAULT: '#F2ECE0',
          soft: '#FAF6EC',
          deep: '#E4DCCC',
          ink: '#1B2420',
          muted: '#6D7872',
        },
        tyrian: {
          DEFAULT: '#5D1049',
          soft: '#7A2564',
          glow: '#C84BA4',
          muted: 'rgba(93, 16, 73, 0.12)',
        },
        banana: {
          DEFAULT: '#F7E7A1',
          soft: '#FBF1C4',
          deep: '#E6CF6B',
        },
        accent: {
          DEFAULT: '#5D1049',
          hover: '#7A2564',
          muted: 'rgba(93, 16, 73, 0.12)',
          light: '#C84BA4',
        },
        surface: {
          primary: '#1B2E24',
          secondary: '#2F4A3A',
          tertiary: '#3A5A47',
          input: '#243D30',
          overlay: 'rgba(14, 27, 20, 0.6)',
        },
        content: {
          primary: '#F2ECE0',
          secondary: '#B8C4BD',
          tertiary: '#6B8A77',
        },
        border: {
          DEFAULT: '#1B2E24',
          hover: '#3A5A47',
          accent: '#5D1049',
        },
        success: { DEFAULT: '#4A8A6A', muted: 'rgba(74, 138, 106, 0.12)' },
        warning: { DEFAULT: '#D9A441', muted: 'rgba(217, 164, 65, 0.12)' },
        danger: { DEFAULT: '#5D1049', muted: 'rgba(93, 16, 73, 0.12)' },
        info: { DEFAULT: '#4A7A8A', muted: 'rgba(74, 122, 138, 0.12)' },
        retro: {
          bg: '#EDE6D5',
          'bg-alt': '#E4DCCC',
          surface: '#FAF6EC',
          text: '#1B2420',
          'text-muted': '#6D7872',
          border: '#D4C8B0',
          accent: '#5D1049',
          'accent-hover': '#7A2564',
          ink: '#0E1B14',
        },
        theme: {
          bg: 'var(--bg-app)',
          elevated: 'var(--bg-elevated)',
          deep: 'var(--bg-deep)',
          input: 'var(--bg-input)',
          text: 'var(--text-primary)',
          'text-secondary': 'var(--text-secondary)',
          'text-muted': 'var(--text-muted)',
          border: 'var(--border-default)',
          'border-hover': 'var(--border-hover)',
          overlay: 'var(--overlay)',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        serif: ['Instrument Serif', 'Playfair Display', 'Georgia', 'serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      fontSize: {
        'xs': ['0.75rem', { lineHeight: '1rem' }],
        'sm': ['0.875rem', { lineHeight: '1.25rem' }],
        'base': ['1rem', { lineHeight: '1.5rem' }],
        'lg': ['1.125rem', { lineHeight: '1.75rem' }],
        'xl': ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '5xl': ['3rem', { lineHeight: '1.1' }],
        '6xl': ['3.75rem', { lineHeight: '1.05' }],
        '7xl': ['4.5rem', { lineHeight: '1.05' }],
      },
      borderRadius: {
        sm: '6px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        '2xl': '20px',
      },
      boxShadow: {
        sm: '0 1px 2px rgba(27, 36, 32, 0.06)',
        md: '0 4px 12px rgba(27, 36, 32, 0.08)',
        lg: '0 8px 24px rgba(27, 36, 32, 0.10)',
        'moss': '0 10px 30px rgba(27, 46, 36, 0.25)',
        'tyrian': '0 8px 24px rgba(93, 16, 73, 0.25)',
      },
      spacing: {
        'sidebar': '240px',
        'sidebar-collapsed': '64px',
        'navbar': '56px',
        'right-panel': '320px',
      },
      maxWidth: {
        'feed': '640px',
        'container': '1280px',
      },
      animation: {
        'fade-in': 'fadeIn 0.2s ease-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'slide-right': 'slideRight 0.2s ease-out',
        'float': 'float 6s ease-in-out infinite',
        'float-delayed': 'float 6s ease-in-out 2s infinite',
        'float-slow': 'float 8s ease-in-out 1s infinite',
        'terminal-scroll': 'terminalScroll 40s linear infinite',
        'blob': 'blob 18s ease-in-out infinite',
        'ribbon': 'ribbon 14s ease-in-out infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px) rotate(0deg)' },
          '50%': { transform: 'translateY(-12px) rotate(1deg)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideRight: {
          '0%': { opacity: '0', transform: 'translateX(-8px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        terminalScroll: {
          '0%': { transform: 'translateY(0)' },
          '100%': { transform: 'translateY(-50%)' },
        },
        blob: {
          '0%, 100%': { transform: 'translate(0, 0) scale(1)' },
          '33%': { transform: 'translate(20px, -30px) scale(1.08)' },
          '66%': { transform: 'translate(-20px, 20px) scale(0.94)' },
        },
        ribbon: {
          '0%, 100%': { transform: 'translateX(-10px) rotate(-2deg)' },
          '50%': { transform: 'translateX(10px) rotate(2deg)' },
        },
      },
    },
  },
  plugins: [],
};
