#!/usr/bin/env bash
# ============================================================
# Generate .env with strong random secrets from .env.example.
# Run once on the server (or locally) before the first
# `docker compose up`.
#
#   bash scripts/generate-env.sh
#
# Refuses to overwrite an existing .env — delete it first if
# you really want to regenerate.
# ============================================================
set -euo pipefail

if [[ -f .env ]]; then
  echo "ERROR: .env already exists. Delete it first to regenerate." >&2
  exit 1
fi

if ! command -v openssl >/dev/null 2>&1; then
  echo "ERROR: openssl not installed." >&2
  exit 1
fi

# 32 url-safe chars from /dev/urandom
rand_pw() { openssl rand -base64 24 | tr -d '/+=' | head -c 32; }

DB_PASSWORD="$(rand_pw)"
REDIS_PASSWORD="$(rand_pw)"
S3_ACCESS_KEY="$(rand_pw)"
S3_SECRET_KEY="$(rand_pw)"
JWT_SECRET="$(openssl rand -base64 44 | tr -d '\n')"

cat > .env <<EOF
# Generated by scripts/generate-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Keep this file out of git. The bucket name is fine as-is.

# ── Database ──
DB_NAME=synora
DB_USER=synora
DB_PASSWORD=${DB_PASSWORD}

# ── Redis ──
REDIS_PASSWORD=${REDIS_PASSWORD}

# ── MinIO (S3-compatible storage) ──
S3_ACCESS_KEY=${S3_ACCESS_KEY}
S3_SECRET_KEY=${S3_SECRET_KEY}
S3_BUCKET=synora-files
S3_REGION=us-east-1

# ── JWT (256-bit, base64) ──
JWT_SECRET=${JWT_SECRET}

# ── Spring ──
SPRING_PROFILE=prod
LOG_LEVEL=INFO

# ── Ports ──
NGINX_PORT=80

# ── HTTPS / backups / monitoring (uncomment when needed) ──
# DOMAIN=example.com
# LETSENCRYPT_EMAIL=admin@example.com
# GRAFANA_ADMIN_PASSWORD=$(rand_pw)
EOF

chmod 600 .env
echo "==> .env written (mode 600). Review with: cat .env"
